resources:
- name: git-repo
  type: git
  source:
    uri: https://github.com/DanielHauge/Metis-Link.git
    branch: master

- name: container
  type: docker-image
  source:
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-hub-username))/metis-link

jobs:
- name: build-docker-image
  public: true
  serial: true
  plan:
  - get: git-repo
    trigger: true
  - put: container
    params:
      build: git-repo
